name: hospital_portal
description: "Indus_Sahulat Hospital Portal"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  date_field: ^6.0.0
  equatable: ^2.0.7
  intl: ^0.18.1
  http: ^1.3.0
  go_router: ^14.8.0
  font_awesome_flutter: ^10.8.0
  toastification: ^3.0.2
  hive_flutter: ^1.1.0
  provider: ^6.1.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

